In [1]:
import pandas as pd
from math import sqrt
import numpy as np
import matplotlib.pyplot as plt

In [2]:
movies_df = pd.read_csv('movies.csv')
ratings_df = pd.read_csv('ratings.csv')

In [3]:
movies_df['year'] = movies_df.title.str.extract('(\(\d\d\d\d\))',expand=False)
movies_df['year'] = movies_df.year.str.extract('(\d\d\d\d)',expand=False)
movies_df['title'] = movies_df.title.str.replace('(\(\d\d\d\d\))', '')
movies_df['title'] = movies_df['title'].apply(lambda x: x.strip())
movies_df

<>:1: SyntaxWarning: invalid escape sequence '\('
<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:3: SyntaxWarning: invalid escape sequence '\('
<>:1: SyntaxWarning: invalid escape sequence '\('
<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:3: SyntaxWarning: invalid escape sequence '\('
C:\Users\abolf\AppData\Local\Temp\ipykernel_1624\2501930358.py:1: SyntaxWarning: invalid escape sequence '\('
  movies_df['year'] = movies_df.title.str.extract('(\(\d\d\d\d\))',expand=False)
C:\Users\abolf\AppData\Local\Temp\ipykernel_1624\2501930358.py:2: SyntaxWarning: invalid escape sequence '\d'
  movies_df['year'] = movies_df.year.str.extract('(\d\d\d\d)',expand=False)
C:\Users\abolf\AppData\Local\Temp\ipykernel_1624\2501930358.py:3: SyntaxWarning: invalid escape sequence '\('
  movies_df['title'] = movies_df.title.str.replace('(\(\d\d\d\d\))', '')

,movieId,title,genres,year
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji (1995),Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men (1995),Comedy|Romance,1995
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II (1995),Comedy,1995
...,...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,2017
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,2017
9739,193585,Flint (2017),Drama,2017
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,2018
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,1991

In [4]:
movies_df = movies_df.drop('genres', axis=1)
movies_df

      movieId                                      title  year
0           1                           Toy Story (1995)  1995
1           2                             Jumanji (1995)  1995
2           3                    Grumpier Old Men (1995)  1995
3           4                   Waiting to Exhale (1995)  1995
4           5         Father of the Bride Part II (1995)  1995
...       ...                                        ...   ...
9737   193581  Black Butler: Book of the Atlantic (2017)  2017
9738   193583               No Game No Life: Zero (2017)  2017
9739   193585                               Flint (2017)  2017
9740   193587        Bungo Stray Dogs: Dead Apple (2018)  2018
9741   193609        Andrew Dice Clay: Dice Rules (1991)  1991

[9742 rows x 3 columns]

In [5]:
ratings_df

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [6]:
ratings_df = ratings_df.drop('timestamp', axis=1)

In [7]:
ratings_df

        userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
...        ...      ...     ...
100831     610   166534     4.0
100832     610   168248     5.0
100833     610   168250     5.0
100834     610   168252     5.0
100835     610   170875     3.0

[100836 rows x 3 columns]

In [8]:
userInput = [
            {'title':'Toy Story', 'rating':3.5},
            {'title':'Jumanji', 'rating':2},
            {'title':"Pulp Fiction", 'rating':5},
            {'title':'Akira', 'rating':4.5}
         ] 
inputMovies = pd.DataFrame(userInput)
inputMovies

          title  rating
0     Toy Story     3.5
1       Jumanji     2.0
2  Pulp Fiction     5.0
3         Akira     4.5

In [9]:
movies_data = [
    {'movieId': 1, 'title': 'Toy Story', 'genres': 'Animation', 'year': 1995},
    {'movieId': 2, 'title': 'Jumanji', 'genres': 'Adventure', 'year': 1995},
    {'movieId': 3, 'title': 'Pulp Fiction', 'genres': 'Crime', 'year': 1994},
    {'movieId': 4, 'title': 'Akira', 'genres': 'Animation', 'year': 1988}
]
movies_df = pd.DataFrame(movies_data)

# User input
userInput = [
    {'title':'Toy Story', 'rating':3.5},
    {'title':'Jumanji', 'rating':2},
    {'title':'Pulp Fiction', 'rating':5},
    {'title':'Akira', 'rating':4.5}
]
inputMovies = pd.DataFrame(userInput)

# Merging
inputId = movies_df[movies_df['title'].isin(inputMovies['title'].tolist())]
inputMovies = pd.merge(inputId, inputMovies, on='title').drop('genres', axis=1).drop('year', axis=1)

# Display result
print(inputMovies)

   movieId         title  rating
0        1     Toy Story     3.5
1        2       Jumanji     2.0
2        3  Pulp Fiction     5.0
3        4         Akira     4.5

In [10]:
inputId

   movieId         title     genres  year
0        1     Toy Story  Animation  1995
1        2       Jumanji  Adventure  1995
2        3  Pulp Fiction      Crime  1994
3        4         Akira  Animation  1988

In [11]:
inputMovies

   movieId         title  rating
0        1     Toy Story     3.5
1        2       Jumanji     2.0
2        3  Pulp Fiction     5.0
3        4         Akira     4.5

In [12]:
userSubset = ratings_df[ratings_df['movieId'].isin(inputMovies['movieId'].tolist())]
userSubset.head()

     userId  movieId  rating
0         1        1     4.0
1         1        3     4.0
516       5        1     4.0
560       6        2     4.0
561       6        3     5.0

In [13]:
userSubsetGroup = userSubset.groupby(['userId'])

In [14]:
userSubsetGroup

In [15]:
userSubsetGroup.get_group(6)

C:\Users\abolf\AppData\Local\Temp\ipykernel_1624\982603703.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  userSubsetGroup.get_group(6)

     userId  movieId  rating
560       6        2     4.0
561       6        3     5.0
562       6        4     3.0

In [16]:
userSubset = ratings_df[ratings_df['movieId'].isin(inputMovies['movieId'].tolist())]
userSubset.head()
userSubsetGroup = userSubset.groupby(['userId'])
userSubsetGroup.get_group(610)

C:\Users\abolf\AppData\Local\Temp\ipykernel_1624\1601213065.py:4: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  userSubsetGroup.get_group(610)

       userId  movieId  rating
99534     610        1     5.0

In [17]:
userSubsetGroup = sorted(userSubsetGroup,  key=lambda x: len(x[1]), reverse=True)

In [18]:
userSubsetGroup[0:3]

[((6,),
       userId  movieId  rating
  560       6        2     4.0
  561       6        3     5.0
  562       6        4     3.0),
 ((19,),
        userId  movieId  rating
  2274      19        1     4.0
  2275      19        2     3.0
  2276      19        3     3.0),
 ((68,),
         userId  movieId  rating
  10360      68        1     2.5
  10361      68        2     2.5
  10362      68        3     2.0)]

In [19]:
userSubsetGroup = userSubsetGroup[0:100]

In [20]:
#Store the Pearson Correlation in a dictionary, where the key is the user Id and the value is the coefficient
pearsonCorrelationDict = {}

#For every user group in our subset
for name, group in userSubsetGroup:
    #Let's start by sorting the input and current user group so the values aren't mixed up later on
    group = group.sort_values(by='movieId')
    inputMovies = inputMovies.sort_values(by='movieId')
    #Get the N for the formula
    nRatings = len(group)
    #Get the review scores for the movies that they both have in common
    temp_df = inputMovies[inputMovies['movieId'].isin(group['movieId'].tolist())]
    #And then store them in a temporary buffer variable in a list format to facilitate future calculations
    tempRatingList = temp_df['rating'].tolist()
    #Let's also put the current user group reviews in a list format
    tempGroupList = group['rating'].tolist()
    #Now let's calculate the pearson correlation between two users, so called, x and y
    Sxx = sum([i**2 for i in tempRatingList]) - pow(sum(tempRatingList),2)/float(nRatings)
    Syy = sum([i**2 for i in tempGroupList]) - pow(sum(tempGroupList),2)/float(nRatings)
    Sxy = sum( i*j for i, j in zip(tempRatingList, tempGroupList)) - sum(tempRatingList)*sum(tempGroupList)/float(nRatings)
    
    #If the denominator is different than zero, then divide, else, 0 correlation.
    if Sxx != 0 and Syy != 0:
        pearsonCorrelationDict[name] = Sxy/sqrt(Sxx*Syy)
    else:
        pearsonCorrelationDict[name] = 0

In [21]:
pearsonCorrelationDict.items()

dict_items([((6,), 0.15554275420956382), ((19,), 0.0), ((68,), -0.8660254037844356), ((91,), 0.0), ((169,), 1.0), ((217,), -0.32732683535398854), ((226,), 0.8660254037844448), ((240,), -0.8660254037844356), ((288,), 0.7559289460184544), ((307,), 0.6546536707079778), ((330,), 0.5960395606792697), ((411,), -0.5636214801906777), ((414,), 0.8660254037844402), ((448,), 0.0), ((470,), 0.0), ((477,), -0.8660254037844402), ((480,), -0.8660254037844356), ((590,), 0.3273268353539884), ((599,), -0.6546536707079768), ((600,), -1.0000000000000007), ((608,), 0.0), ((1,), 0), ((18,), 1.0), ((21,), 0), ((27,), -1.0), ((32,), 0), ((43,), 0), ((44,), 0), ((51,), -1.0), ((64,), -1.0), ((82,), -1.0), ((93,), -1.0), ((103,), 0), ((107,), -1.0), ((112,), 1.0), ((117,), 0), ((135,), 1.0), ((140,), -1.0), ((144,), 1.0), ((151,), -1.0), ((153,), 0), ((160,), 0), ((177,), 1.0), ((179,), 0), ((186,), 0), ((202,), 0), ((219,), 1.0), ((232,), -1.0), ((249,), 0), ((269,), -1.0), ((270,), -1.0), ((274,), 1.0), ((276,), 0), ((294,), -1.0), ((298,), 1.0), ((304,), 1.0), ((308,), -1.0), ((321,), -1.0), ((322,), 1.0), ((323,), -1.0), ((337,), 0), ((347,), 1.0), ((353,), 1.0), ((357,), 1.0), ((359,), 1.0), ((373,), 0), ((380,), 0), ((381,), -1.0), ((432,), -1.0), ((434,), 1.0), ((436,), 0), ((456,), -1.0), ((474,), 1.0), ((476,), 0), ((483,), 0), ((484,), 1.0), ((492,), 0), ((501,), 1.0), ((517,), 1.0), ((525,), 1.0), ((534,), -1.0), ((544,), 0), ((555,), 1.0), ((559,), 1.0), ((561,), 0), ((570,), 1.0), ((573,), 1.0), ((594,), 0), ((604,), -1.0), ((605,), 1.0), ((5,), 0), ((7,), 0), ((8,), 0), ((14,), 0), ((15,), 0), ((17,), 0), ((20,), 0), ((31,), 0), ((33,), 0), ((40,), 0)])

In [22]:
pearsonDF = pd.DataFrame.from_dict(pearsonCorrelationDict, orient='index')
pearsonDF.columns = ['similarityIndex']
pearsonDF['userId'] = pearsonDF.index
pearsonDF.index = range(len(pearsonDF))
pearsonDF.head()

   similarityIndex  userId
0         0.155543    (6,)
1         0.000000   (19,)
2        -0.866025   (68,)
3         0.000000   (91,)
4         1.000000  (169,)

In [30]:
topUsers=pearsonDF.sort_values(by='similarityIndex', ascending=False)[0:50]
topUsers.head()

    similarityIndex  userId
22              1.0   (18,)
34              1.0  (112,)
4               1.0  (169,)
36              1.0  (135,)
69              1.0  (434,)

In [33]:
print(topUsers['userId'].head(), topUsers['userId'].dtype)
print(ratings_df['userId'].head(), ratings_df['userId'].dtype)

22     (18,)
34    (112,)
4     (169,)
36    (135,)
69    (434,)
Name: userId, dtype: object object
0    1
1    1
2    1
3    1
4    1
Name: userId, dtype: object object

In [34]:
ratings_df[ratings_df['userId'].isin(topUsers['userId'])].shape

(0, 3)

In [37]:
# Convert 'userId' in topUsers
topUsers['userId'] = topUsers['userId'].apply(lambda x: x[0] if isinstance(x, tuple) else x)
topUsers['userId'] = topUsers['userId'].astype(int)

# Convert 'userId' in ratings_df if needed
ratings_df['userId'] = ratings_df['userId'].astype(int)

# Now try merging again
topUsersRating = topUsers.merge(ratings_df, on='userId', how='inner')
topUsersRating.head()

   similarityIndex  userId  movieId  rating
0              1.0      18        1     3.5
1              1.0      18        2     3.0
2              1.0      18        6     4.0
3              1.0      18       16     4.5
4              1.0      18       32     4.0

In [38]:
#Multiplies the similarity by the user's ratings
topUsersRating['weightedRating'] = topUsersRating['similarityIndex']*topUsersRating['rating']
topUsersRating.head()

   similarityIndex  userId  movieId  rating  weightedRating
0              1.0      18        1     3.5             3.5
1              1.0      18        2     3.0             3.0
2              1.0      18        6     4.0             4.0
3              1.0      18       16     4.5             4.5
4              1.0      18       32     4.0             4.0

In [39]:
tempTopUsersRating = topUsersRating.groupby('movieId').sum()[['similarityIndex','weightedRating']]
tempTopUsersRating.columns = ['sum_similarityIndex','sum_weightedRating']
tempTopUsersRating.head()

         sum_similarityIndex  sum_weightedRating
movieId
1                  29.066000          119.208951
2                  29.221543           88.679192
3                   7.221543           30.358007
4                   0.155543            0.466628
5                   6.104824           17.176276

In [40]:
#Creates an empty dataframe
recommendation_df = pd.DataFrame()
#Now we take the weighted average
recommendation_df['weighted average recommendation score'] = tempTopUsersRating['sum_weightedRating']/tempTopUsersRating['sum_similarityIndex']
recommendation_df['movieId'] = tempTopUsersRating.index
recommendation_df.head()

         weighted average recommendation score  movieId
movieId
1                                     4.101319        1
2                                     3.034720        2
3                                     4.203812        3
4                                     3.000000        4
5                                     2.813558        5

In [41]:
recommendation_df = recommendation_df.sort_values(by='weighted average recommendation score', ascending=False)
recommendation_df.head(10)

         weighted average recommendation score  movieId
movieId
89904                                      5.0    89904
176371                                     5.0   176371
633                                        5.0      633
93320                                      5.0    93320
893                                        5.0      893
93008                                      5.0    93008
25906                                      5.0    25906
8580                                       5.0     8580
4117                                       5.0     4117
3673                                       5.0     3673

In [52]:
movies_df.loc[movies_df['movieId'].isin(recommendation_df.head(10)['movieId'].tolist())]

Empty DataFrame
Columns: [movieId, title, genres, year]
Index: []